### ISSUE TITLE
Issues in December 2017 Article

### ISSUE THREAD

**Issue by raghump** [SrirangaDigital/samajamukhi#1]
1) ಕನ್ನಡಕ್ಕೆ ಇನ್ನೊಂದು ಕವಿರಾಜಮಾರ್ಗ ಲಿಂಕ್ ಕೊಡಬೇಕಾಗಿದೆ. 

samajamukhi/application/views/flat/articles/article-20171202.xx.03/index.php

2) Images of article ಕನ್ನಡದ ಮನಸ್ಸು ಇಂದು ಮುಚ್ಚುತ್ತಿದೆಯೆ? is missing in link and also not appear in images folder

path appear in index.php file is :

images/201712/0007b.jpg
images/201712/0009a.jpg

**Comment by kishorssk** [comment]
Updated
