### ISSUE TITLE
Issues in April 2018

### ISSUE THREAD

**Issue by raghump** [SrirangaDigital/samajamukhi#2]
ಎಲ್ಲಾ ಆರ್ಟಿಲ್ಗ‌ಳ ಮೇಲ್ಬಾಗದಲ್ಲಿ ಬರುವ ದಿನಾಂಕ ಮತ್ತು ತಿಂಗಳು 2nd May 2018 ಎಂದು ಆಗಿದೆ, ಅದು 2nd April 2018 ಎಂದು ಆಗಬೇಕು

**Comment by kishorssk** [comment]
Updated
